article/urls.py
from django.urls import path
from . import views

# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    path('list/', views.article_list, name='article_list'),
    path('detail/<int:id>/', views.article_detail, name='article_detail'),
    path('create/', views.article_create, name='article_create'),
    path('delete/<int:id>', views.article_delete, name='article_delete'),
    path('safe_delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('update/<int:id>/', views.article_update, name='article_update'),

]

blog_yzx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static

def index(request):
    return render(request, 'base.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('', index, name='index'),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('commment/', include('comment.urls', namespace='comment')),

]

# 配置图像的url
urlpatterns += static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('edit/<int:id>/', views.profile_edit, name='edit')
]

templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}
{#<!DOCTYPE html>#}
{#<!-- 网站主语言 -->#}
<html lang="zh-cn">

<head>
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
</body>

</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.dusaiphoto.com 2018</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="#">我的博客</a>

    <!-- 导航入口 -->
    <div>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
            </li>

            {% if user.is_authenticated %}
            <!-- 如果用户已经登录，则显示用户名下拉框 -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
                    <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                  <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
                </div>
            </li>
            <!-- 如果用户未登录，则显示 “登录” -->
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                </li>
            <!-- if 语句在这里结束 -->
            {% endif %}

            </ul>
    </div>


  </div>
</nav>

{% if user.is_authenticated %}
<form
    style="display:none;"
    id="user_delete"
    action="{% url 'userprofile:delete' user.id %}"
    method="POST"
>
{% csrf_token %}
    <button type="submit">发送</button>
</form>
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function(index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}